services:
  shgpu-table:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GO_VERSION: "2:1.19.3"
        NODE_VERSION: "18.12.1"
    command: sleep infinity
    user: dluki
    volumes:
      - .:/workspace:cached
    ports:
      - 3000:3000
    depends_on:
      - bot-postgres
      - postgres
      - redis
    networks:
      - shgpu-table-dev
    links:
      - postgres
      - bot-postgres

  bot-postgres:
    container_name: bot-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shgpu-table-bot
    ports:
      - 5433:5433
    command: -p 5433
    volumes:
      - .:/var/lib/postgresql/shgpu-table
      - ./apps/telegram-bot/src/db/init.sql:/docker-entrypoint-initdb.d/bot-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shgpu-table-bot"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512MB
    networks:
      - shgpu-table-dev
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    # volumes:
    # - .:/var/lib/postgresql/shgpu-table
    # - ./apps/parser/src/db/queries/init.sql:/docker-entrypoint-initdb.d/parser-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shgpu-table"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512MB
    networks:
      - shgpu-table-dev
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - shgpu-table-dev
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "danluki02@yandex.ru"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   ports:
  #     - 5050:80
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512MB
  #   networks:
  #     - shgpu-table-dev
  redis:
    restart: unless-stopped
    image: redis/redis-stack:latest
    networks:
      - shgpu-table-dev
    ports:
      - 6379:6479
networks:
  shgpu-table-dev:
    driver: bridge
